### ISSUE TITLE
With "Chunk optimizations" Enabled, Chunks Not Saving When Certain Blocks Placed, Only After Certain Others Are. v1.21-1.21.2-1.1.6.1

### ISSUE THREAD

**Issue by MindeKing** [ITsMrToad/PalladiumMod#119]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

With the setting "Chunk optimizations" enabled, it would appear as if chunks do not save if non-solid or non-full blocks only are placed in them before exiting a world (also resulting in a loss of items). Rather, chunks will apparently only save after a full-block is placed in them.
With the setting disabled, worlds appear to save as expected.

See video below for an example of a chunk not saving with the setting enabled, then saving after it is disabled.
https://github.com/user-attachments/assets/09cd9304-fc4b-4f4b-9bd2-022883eccfb1

Appears to be similar to https://github.com/ITsMrToad/PalladiumMod/issues/112, however, no other superfluous mods are present, as can be seen in the video.

### Steps to reproduce

1. Create new instance of Minecraft 1.21.1 (with ATLauncher, in this case)
2. Place the following mods in the instance's "mods" folder:
- [fabric-api-0.115.6+1.21.1](https://modrinth.com/mod/fabric-api/version/0.115.6+1.21.1)
- [modmenu-11.0.3](https://modrinth.com/mod/modmenu/version/11.0.3)
- [ToadLib-1.21-1.21.1-1.2.7](https://modrinth.com/mod/toadlib/version/1.2.7-1.21-1.21.1-fabric)
- [Palladium-1.21-1.21.2-1.1.6.1](https://modrinth.com/mod/mpalladium/version/1.1.6.1-1.21-1.21.2)
3. Open Minecraft
4. Create / join a world
5. Place down blocks which you suspect won't save in different chunks
6. Leave and rejoin the world to see which chunks do and don't load

### What version of the palladium are you using?

1.1.6.1

**Comment by ITsMrToad** [comment]
Fixed in 1.1.7(I guess). Tested on chests and furnances, as well as non-solid blocks.

**Comment by GogUwU** [comment]
this still happens on 1.1.7 neoforge 1.21.1

https://github.com/user-attachments/assets/c76b8b1a-96dc-4c6d-8bc8-3890f6d53f6d

modlist:
Create (https://modrinth.com/mod/LNytGWDc) [6.0.4]
Palladium (https://modrinth.com/mod/JNRr4jji) [1.1.7]
ToadLib (https://modrinth.com/mod/CYQ7VYrM) [1.3.2]
(create didn't affect testing in any way i just had it)
