### ISSUE TITLE
The server cannot start with this mod

### ISSUE THREAD

**Issue by ifloppy** [ITsMrToad/PalladiumMod#89]
### What operating systems are you seeing the problem on?

Linux

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

Server version: fabric-server-mc.1.21.4-loader.0.16.10-launcher.1.0.1

**Notes:**

1. When using version 1.0.9.5 of 1.21.1, I did not encounter this issue.
2. The problem started after upgrading to version 1.21.1-1.1.3.
3. I then tried upgrading the game version to 1.21.4, and using Palladium-1.21.4-1.1.3, but the issue persisted.
4. Currently, I am using ToadLib version: ToadLib-1.21.2-1.21.4-1.2.5.

Related log:
```
[main/WARN]: Error loading class: com/mr_toad/palladium/core/config/PalladiumConfig (java.lang.RuntimeException: Cannot load class com.mr_toad.palladium.core.config.PalladiumConfig in environment type SERVER)
```
Full log: [latest(2).log](https://github.com/user-attachments/files/18779859/latest.2.log)

I would appreciate any assistance or solutions to resolve this issue. Thank you in advance for your help.

### What version of the palladium are you using?

Palladium-1.21.4-1.1.3

**Comment by ITsMrToad** [comment]
Try running it on the client. 
And a quick question, how does ToadLib work on the client?

**Comment by ifloppy** [comment]
Palladium and ToadLib can work properly on the client. But I want to run it on the client as the supported platforms are both client and server on Modrinth.

**Comment by nedvi** [comment]
I have same issue on 1.21.1. No problems on client but server throws this error.

**Comment by prismaticNett** [comment]
same issue here on 1.20.1 and on forge

**Comment by ITsMrToad** [comment]
If they do work properly on the client, why not use them there?

**Comment by DigitalityScripts** [comment]
because it says on modrinth that palladium is for both server and client yet it does not work on servers at ALL

**Comment by ifloppy** [comment]
> If they do work properly on the client, why not use them there?

Because the platform you chose is "Both Client and Server". And the older version of Palladium works on server. 

Will this project drop the server side support?

**Comment by Alexander020304** [comment]
i would like to run this on my server can this get an a fix?

**Comment by ITsMrToad** [comment]
Palladium consists mostly of client-side enhancements, and I think to run the mod on the server I'd need to rewrite the config system in ToadLib, but I'll still try to make it server-compatible.

**Comment by Alexander020304** [comment]
thanks. i need all the performance i can get.

**Comment by Poopooracoocoo** [comment]
On Modrinth Palladium is labelled as being client sided. The fabric.mod.json does not match this.

**Comment by ITsMrToad** [comment]
> On Modrinth Palladium is labelled as being client sided. The fabric.mod.json does not match this.

Fixed(probably) in 1.1.6

**Comment by ifloppy** [comment]
> > On Modrinth Palladium is labelled as being client sided. The fabric.mod.json does not match this.
> 
> Fixed(probably) in 1.1.6

It's not fixed. I'm trying to start the server with Palladium 1.1.6 (and ToadLib 1.3.0), but I get this: 

```
[15:23:00] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[15:23:00] [main/WARN]: Error loading class: com/mr_toad/palladium/core/config/PalladiumConfig (java.lang.RuntimeException: Cannot load class com.mr_toad.palladium.core.config.PalladiumConfig in environment type SERVER)
[15:23:00] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2487 failed
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.10.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [core.jar:1.0.1]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2487 failed
        at knot/net.minecraft.class_9135.method_57998(class_9135.java:250) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9135.<clinit>(class_9135.java:261) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8824.<clinit>(class_8824.java:41) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2588.<clinit>(class_2588.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2561.method_43471(class_2561.java:232) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_155.<clinit>(class_155.java:239) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:70) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.10.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2487 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.10.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_9135.method_57998(class_9135.java:250) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9135.<clinit>(class_9135.java:261) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8824.<clinit>(class_8824.java:41) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2588.<clinit>(class_2588.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2561.method_43471(class_2561.java:232) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_155.<clinit>(class_155.java:239) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:70) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.10.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.10.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_9135.method_57998(class_9135.java:250) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9135.<clinit>(class_9135.java:261) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_8824.<clinit>(class_8824.java:41) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2588.<clinit>(class_2588.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2561.method_43471(class_2561.java:232) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_155.<clinit>(class_155.java:239) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:70) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.10.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mr_toad_palladium.mixins.json:NbtCompoundMixin from mod mr_toad_palladium during activity: [Transform -> Method straightElementMap(Ljava/util/Map;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> GETFIELD -> com/mr_toad/palladium/core/config/PalladiumConfig::nbtOptimizations:Lcom/mr_toad/lib/api/config/entry/BoolEntry;]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.10.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_9135.method_57998(class_9135.java:250) ~[server-intermediary.jar:?]
```

**Comment by ITsMrToad** [comment]
Use Palladium on the client, I don't have time to do that right now and the most I can do is split Palladium into two mods in the future.

**Comment by Poopooracoocoo** [comment]
Could you set the environment in the FMJ then?

**Comment by ITsMrToad** [comment]
> Could you please set the environment in FMJ?

You mean FML? It works a bit more complicated with forge, but I can try it.

**Comment by Poopooracoocoo** [comment]
I meant the fabric.mod.json
