### ISSUE TITLE
minecraft crash if doing this

### ISSUE THREAD

**Issue by rakantoh** [ITsMrToad/PalladiumMod#96]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

if i put a composter above of a hopper, the game crashes, after this, it's impossible enter to the world where the composter is above of the hopper, disabling palladium, i can enter to the world normally, and if remove/delete the composter and/or the hopper, i can enable palladium and enter the world again without issues. 

### Steps to reproduce

put a hopper, and above put a composter.

### What version of the palladium are you using?

1.1.5

**Comment by DaFtuf** [comment]
indeed

**Comment by ArthusMachima** [comment]
had the same problem

**Comment by ITsMrToad** [comment]
Fixed in 1.1.6

**Comment by PhyX-Meow** [comment]
This is not fixed I unfortunately. At least I see no actual code update in commit history. And this does happen on latest version. Could you please fix it?
